[package]
name = "swim-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
snafu = "0.8.4"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
