name: Publish

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protobuf Compiler (protoc) 
        run: sudo apt-get install -y protobuf-compiler
      - name: Dryrun swim-rs
        run: cargo publish --all-features --dry-run

      # - name: Publish swim-rs
      #   # Only publish if it's a tag and the tag is not a pre-release
      #   if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-') }}
      #   run: cargo publish --all-features
      #   env:
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
